#!/bin/bash

set -xe

server_prefix="localhost:5000/"

if [ $# -ne 1 ]; then
	echo "Provide a docker image name before proceeding."
	exit 1;
fi

sudo docker run -d -p 7777:7777 $server_prefix$1 node /proj/calculator/index.js
aws s3 cp /registry s3://finep2 --recursive